src/Entity/ForumTag.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ForumTagRepository")
 * @ORM\Table(uniqueConstraints={
 *     @ORM\UniqueConstraint(name="forum_tag_name_idx", columns={"name"}),
 *     @ORM\UniqueConstraint(name="forum_tag_normalized_name_idx", columns={"normalized_name"}),
 * })
 */
class ForumTag {
    /**
     * @ORM\Column(type="uuid")
     * @ORM\Id()
     *
     * @var UuidInterface
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity="Forum", mappedBy="tags", fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"name": "DESC"})
     *
     * @var Forum[]|Collection
     */
    private $forums;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     *
     * @var string
     */
    private $normalizedName;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string
     */
    private $description;

    public function __construct(
        string $name,
        string $description = null
    ) {
        $this->id = Uuid::uuid4();
        $this->forums = new ArrayCollection();
        $this->setName($name);
        $this->description = $description;
    }

    public function getId(): UuidInterface {
        return $this->id;
    }

    public function getForums(): array {
        $criteria = Criteria::create()
            ->orderBy(['normalizedName' => 'ASC']);

        return $this->forums->matching($criteria)->toArray();
    }

    public function hasForum(Forum $forum): bool {
        return $this->forums->contains($forum);
    }

    public function addForum(Forum $forum): void {
        if (!$this->forums->contains($forum)) {
            $this->forums->add($forum);
        }

        if (!$forum->hasTag($this)) {
            $forum->addTags($this);
        }
    }

    public function removeForum(Forum $forum): void {
        $this->forums->removeElement($forum);

        if ($forum->hasTag($this)) {
            $forum->removeTags($this);
        }
    }

    public function getForumCount(): int {
        return $this->forums->count();
    }

    public function getName(): string {
        return $this->name;
    }

    public function setName(string $name): void {
        $this->name = $name;
        $this->normalizedName = self::normalizeName($name);
    }

    public function getNormalizedName(): string {
        return $this->normalizedName;
    }

    public static function normalizeName(string $name): string {
        return mb_strtolower($name, 'UTF-8');
    }

    public function getDescription(): ?string {
        return $this->description;
    }

    public function setDescription(?string $description): void {
        $this->description = $description;
    }
}

src/Form/ForumTagType.php
<?php

namespace App\Form;

use App\DataObject\ForumTagData;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class ForumTagType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options): void {
        $builder
            ->add('name', TextType::class, [
                'help' => 'help.will_appear_in_the_url',
                'label' => 'label.name',
            ])
            ->add('description', TextareaType::class, [
                'label' => 'label.description',
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void {
        $resolver->setDefaults([
            'data_class' => ForumTagData::class,
            'validation_groups' => ['update_forum_tag'],
        ]);
    }
}

src/Form/Type/ForumTagsType.php
<?php

namespace App\Form\Type;

use App\Form\DataTransformer\ForumTagDataListToStringsTransformer;
use App\Form\DataTransformer\TagArrayToStringTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;

final class ForumTagsType extends AbstractType {
    /**
     * @var TagArrayToStringTransformer
     */
    private $tagArrayToStringTransformer;

    /**
     * @var ForumTagDataListToStringsTransformer
     */
    private $forumTagDataListToStringsTransformer;

    public function __construct(
        TagArrayToStringTransformer $tagArrayToStringTransformer,
        ForumTagDataListToStringsTransformer $forumTagDataListToStringsTransformer
    ) {
        $this->tagArrayToStringTransformer = $tagArrayToStringTransformer;
        $this->forumTagDataListToStringsTransformer = $forumTagDataListToStringsTransformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void {
        $builder
            ->addModelTransformer($this->tagArrayToStringTransformer)
            ->addModelTransformer($this->forumTagDataListToStringsTransformer)
        ;
    }

    public function getParent(): string {
        return TextareaType::class;
    }
}

src/Controller/ForumTagController.php
<?php

namespace App\Controller;

use App\Entity\ForumTag;
use App\Form\ForumTagType;
use App\DataObject\ForumTagData;
use App\Repository\ForumTagRepository;
use App\SubmissionFinder\Criteria;
use App\SubmissionFinder\SubmissionFinder;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Entity("tag", expr="repository.findByNameOrRedirectToCanonical(name, 'name')")
 */
final class ForumTagController extends AbstractController {
    public function list(ForumTagRepository $tags, int $page): Response {
        return $this->render('forum_tag/list.html.twig', [
            'tags' => $tags->findPaginated($page),
        ]);
    }

    public function tag(ForumTag $tag, ?string $sortBy, SubmissionFinder $submissionFinder): Response {
        $criteria = (new Criteria($sortBy))
            ->showForums(...$tag->getForums())
            ->excludeHiddenForums()
            ->excludeBlockedUsers();

        $submissions = $submissionFinder->find($criteria);

        return $this->render('forum_tag/tag.html.twig', [
            'sort_by' => $submissionFinder->getSortMode($sortBy),
            'submissions' => $submissions,
            'tag' => $tag,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @IsGranted("ROLE_ADMIN", statusCode=403)
     */
    public function edit(ForumTag $tag, Request $request, EntityManagerInterface $em): Response {
        $data = ForumTagData::createFromForumTag($tag);

        $form = $this->createForm(ForumTagType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data->updateForumTag($tag);

            $em->flush();

            return $this->redirectToRoute('forum_tag', ['name' => $tag->getName()]);
        }

        return $this->render('forum_tag/edit.html.twig', [
            'tag' => $tag,
            'form' => $form->createView(),
        ]);
    }
}

templates/forum_tag/_form.html.twig
{% from '_macros/form.html.twig' import button_row %}
{{ form_start(form) }}
  {{ form_row(form.name) }}
  {{ form_row(form.description, { attr: { rows: 8 } }) }}
  {{ button_row(editing ? 'action.save'|trans : 'action.create'|trans) }}
{{ form_end(form) }}

templates/forum_tag/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'action.new_forum_tag'|trans %}

{% block body %}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {{ include('forum_tag/_form.html.twig', {editing: false, form: form}, with_context=false) }}
{% endblock %}

templates/forum_tag/edit.html.twig
{% extends 'base.html.twig' %}

{% block title 'title.editing_forum_tag'|trans({ '%tag%': tag.name }) %}

{% block body %}
  <h1>{{ 'title.editing_forum_tag'|trans({
    '%tag%': '<a href="%s">%s</a>'|format(
      path('forum_tag', { name: tag.name })|e,
      tag.name|e
    )})|raw }}</h1>

  {{ include('forum_tag/_form.html.twig', { form: form, editing: true }, with_context=false) }}
{% endblock %}

templates/forum_tag/list.html.twig
{% extends 'base.html.twig' %}

{% block title 'label.tags'|trans %}

{% set can_manage_tags = is_granted('ROLE_ADMIN') %}

{% block head %}
  {{ include('_includes/meta_pagination.html.twig', { pager: tags }, with_context=false) }}
{% endblock head %}

{% block body %}
  {{ include('forum/_list_nav.html.twig', { active: 'tags' }, with_context=false) }}

  <h1 class="page-heading">{{ block('title') }}</h1>

  {% embed '_layouts/table.html.twig' with { items: tags } %}
    {% block header %}
      <th>{{ 'label.name'|trans }}</th>
      <th class="table__shrink">{{ 'nav.forums'|trans }}</th>
      {% if can_manage_tags %}
        <th class="table__shrink"></th>
      {% endif %}
    {% endblock header %}

    {% block row %}
      <td>
        <a href="{{ path('forum_tag', { name: item.name }) }}">
          {{- item.name -}}
        </a>
      </td>
      <td class="table__shrink">
        {{ 'label.forums_count'|trans({ '%count%': item.forumCount }) }}
      </td>
      {% if can_manage_tags %}
        <td class="table__shrink">
          <a href="{{ path('forum_tag_edit', { name: item.name }) }}"
             class="button button--secondary button--small inline">
            {{- 'action.edit'|trans -}}
          </a>
        </td>
      {% endif %}
    {% endblock row %}
  {% endembed %}
{% endblock body %}

templates/forum_tag/tag.html.twig
{% extends 'base.html.twig' %}

{% from '_macros/icon.html.twig' import icon %}
{% from '_macros/post_nav.html.twig' import submission_sort, submission_time %}
{% from 'submission/_macros.html.twig' import submission %}

{% block title tag.name %}

{% block head %}
  {{ parent() }}
  {{ include('_includes/meta_pagination.html.twig', { pager: submissions }, with_context=false) }}
{% endblock %}

{% block sidebar %}
  <section class="sidebar__section flow">
    <h2 class="sidebar__title">
      <span class="flex flex--slim-gutters">
        {{ icon('tag') }}
        <span>{{ tag.name }}</span>
      </span>
    </h2>

    {% if tag.description is not empty %}
      <div class="text-flow">
        {{ tag.description|cached_markdown|raw }}
      </div>
    {% endif %}

    {% if is_granted('ROLE_ADMIN') %}
      <nav>
        <p>
          <a href="{{ path('forum_tag_edit', { name: tag.name }) }}"
             class="button button--small inline">
            {{- 'action.edit'|trans -}}
          </a>
        </p>
      </nav>
    {% endif %}
  </section>

  <section class="sidebar__section flow">
    <h2 class="sidebar__title">{{ 'label.forums_with_this_tag'|trans }}</h2>

    <ul class="flex flex--slim-gutters unlistify">
      {% for forum in tag.forums %}
        <li>
          <a href="{{ path('forum', { forum_name: forum.name }) }}"
             class="button button--secondary button--small">
            {{- forum.name -}}
          </a>
        </li>
      {% endfor %}
    </ul>
  </section>
{% endblock %}

{% block body %}
  <h1 class="page-heading">{{ tag.name }}</h1>

  <nav>
    <ul class="unlistify flex">
      {{ submission_sort(sort_by) }}
      {{ submission_time(sort_by) }}
    </ul>
  </nav>

  {% for submission in submissions %}
    {{ submission(submission) }}
  {% endfor %}

  {{ include('_includes/pagination.html.twig', { pager: submissions }, with_context=false) }}
{% endblock body %}