src/Entity/IpBan.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IpBanRepository")
 * @ORM\Table(name="bans")
 */
class IpBan {
    /**
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue()
     * @ORM\Id()
     *
     * @var int|null
     */
    private $id;

    /**
     * @ORM\Column(type="inet")
     *
     * @var string
     */
    private $ip;

    /**
     * @ORM\Column(type="text", nullable=true)
     *
     * @var string
     */
    private $reason;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="ipBans")
     *
     * @var User|null
     */
    private $user;

    /**
     * @ORM\JoinColumn(nullable=false)
     * @ORM\ManyToOne(targetEntity="User")
     *
     * @var User
     */
    private $bannedBy;

    /**
     * @ORM\Column(type="datetimetz_immutable")
     *
     * @var \DateTimeImmutable
     */
    private $timestamp;

    /**
     * @ORM\Column(name="expiry_date", type="datetimetz_immutable", nullable=true)
     *
     * @var \DateTimeImmutable
     */
    private $expires;

    public function __construct(
        string $ip,
        string $reason,
        ?User $user,
        User $bannedBy,
        \DateTimeInterface $expires = null
    ) {
        [$network, $mask] = array_pad(explode('/', $ip), 2, null);

        if (!filter_var($network, FILTER_VALIDATE_IP)) {
            throw new \InvalidArgumentException('$ip must be valid IP with optional CIDR range');
        }

        if ($mask !== null && (
            !is_numeric($mask) ||
            $mask < 0 ||
            $mask > (strpos($network, ':') !== false ? 128 : 32)
        )) {
            throw new \InvalidArgumentException('Invalid CIDR mask');
        }

        if ($expires instanceof \DateTime) {
            $expires = \DateTimeImmutable::createFromMutable($expires);
        }

        $this->ip = $ip;
        $this->reason = $reason;
        $this->user = $user;
        $this->bannedBy = $bannedBy;
        $this->expires = $expires;
        $this->timestamp = new \DateTimeImmutable('@'.time());
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getIp(): string {
        if (strpos($this->ip, ':') !== false) {
            return explode('/128', $this->ip)[0];
        }

        return explode('/32', $this->ip)[0];
    }

    public function isRangeBan(): bool {
        return strpos($this->getIp(), '/') !== false;
    }

    public function getReason(): string {
        return $this->reason;
    }

    public function getUser(): ?User {
        return $this->user;
    }

    public function getBannedBy(): User {
        return $this->bannedBy;
    }

    public function getTimestamp(): \DateTimeImmutable {
        return $this->timestamp;
    }

    public function getExpires(): ?\DateTimeImmutable {
        return $this->expires;
    }
}

src/Controller/BanController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\BanUserType;
use App\Form\IpBanType;
use App\Form\Model\IpBanData;
use App\Form\Model\UserBanData;
use App\Form\UnbanUserType;
use App\Repository\IpBanRepository;
use App\Repository\UserBanRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @IsGranted("ROLE_ADMIN", statusCode=403)
 * @Entity("user", expr="repository.findOneOrRedirectToCanonical(username, 'username')")
 */
final class BanController extends AbstractController {
    public function userBans(UserBanRepository $repository, int $page): Response {
        return $this->render('ban/user_bans.html.twig', [
            'bans' => $repository->findActiveBans($page),
        ]);
    }

    public function banUser(User $user, UserRepository $repository, EntityManagerInterface $em, Request $request): Response {
        $data = new UserBanData($repository->findIpsUsedByUser($user));

        $form = $this->createForm(BanUserType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ban = $data->toUserBan($user, $this->getUser(), true);

            if ($form->get('ban_ip')->getData()) {
                foreach ($data->toIpBans($user, $this->getUser()) as $ipBan) {
                    $em->persist($ipBan);
                }
            }

            $em->persist($ban);
            $em->flush();

            return $this->redirectToRoute('user_bans');
        }

        return $this->render('ban/ban_user.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    public function unbanUser(User $user, EntityManagerInterface $em, Request $request): Response {
        $data = new UserBanData();

        $form = $this->createForm(UnbanUserType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $unban = $data->toUserBan($user, $this->getUser(), false);

            $em->persist($unban);

            if ($form->get('unban_ips')->getData()) {
                foreach ($user->getIpBans() as $ipBan) {
                    $em->remove($ipBan);
                }
            }

            $em->flush();

            $this->addFlash('success', 'flash.user_was_unbanned');

            return $this->redirectToRoute('user_bans');
        }

        return $this->render('ban/unban_user.html.twig', [
            'form' => $form->createView(),
            'user' => $user,
        ]);
    }

    public function ipBans(int $page, IpBanRepository $repository): Response {
        return $this->render('ban/ip_bans.html.twig', [
            'bans' => $repository->findAllPaginated($page),
        ]);
    }

    public function banIp(Request $request, EntityManagerInterface $em): Response {
        $data = new IpBanData();

        $form = $this->createForm(IpBanType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ban = $data->toIpBan($this->getUser());

            $em->persist($ban);
            $em->flush();

            $this->addFlash('success', 'flash.ban_added');

            return $this->redirectToRoute('ip_bans');
        }

        return $this->render('ban/ban_ip.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function unbanIps(Request $request, IpBanRepository $repository, EntityManagerInterface $em): Response {
        $this->validateCsrf('unban_ips', $request->request->get('token'));

        $ids = array_filter((array) $request->request->get('ban'), static function ($id) {
            return \is_int(+$id);
        });

        foreach ($repository->findBy(['id' => $ids]) as $ban) {
            $em->remove($ban);
        }

        $em->flush();

        return $this->redirectToRoute('ip_bans');
    }
}

templates/ban/_tabs.html.twig
<nav class="flex flex--guttered">
  <ul class="unlistify flex">
    <li>
      <a href="{{ path('user_bans') }}" class="tab {{ page == 'user_bans' ? 'tab--active' }}">
        {{- 'nav.user_bans'|trans -}}
      </a>
    </li>
    <li>
      <a href="{{ path('ip_bans') }}" class="tab {{ page == 'ip_bans' ? 'tab--active' }}">
        {{- 'nav.ip_bans'|trans -}}
      </a>
    </li>
  </ul>
</nav>

templates/ban/ban_ip.html.twig
{% extends 'base.html.twig' %}
{% from '_macros/form.html.twig' import button_row %}

{% block site_nav_active 'places' %}
{% block site_nav_main_menu_active 'admin' %}
{% block site_nav_admin_menu_active 'bans' %}
{% block title 'ban_add.title'|trans %}

{% block body %}
  {{ include('ban/_tabs.html.twig', {page: 'ip_bans'}, with_context=false) }}
  <h1 class="page-heading">{{ block('title') }}</h1>

  {{ form_start(form) }}
    {{ form_row(form.ip) }}

    {{ form_row(form.reason) }}

    {{ form_row(form.expires) }}

    {{ form_row(form.user) }}

    {{ button_row('action.ban'|trans) }}
  {{ form_end(form) }}
{% endblock body %}

templates/ban/ban_user.html.twig
{% extends 'base.html.twig' %}
{% from '_macros/form.html.twig' import button_row %}
{% from 'user/_macros.html.twig' import user_link %}

{% block title block('html_title')|striptags %}

{% block body %}
  {{ include('ban/_tabs.html.twig', {page: 'user_bans'}, with_context=false) }}

  <h1 class="page-heading">
    {% block html_title %}
      {{ 'title.ban_user'|trans({'%user%': user_link(user, {prefix: true})})|raw }}
    {% endblock %}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.reason) }}
    {{ form_row(form.expires) }}
    {{ form_row(form.ban_ip) }}
    {{ form_row(form.ips) }}
    {{ button_row('action.ban'|trans) }}
  {{ form_end(form) }}
{% endblock %}

templates/ban/banned.html.twig
{% extends 'base.html.twig' %}

{% block title 'banned.title'|trans %}
{% block sidebar ' ' %}

{% block body %}
  <h1>{{ 'banned.title'|trans }}</h1>

  {% if user_ban %}
    <p>{{ 'banned.banned_account'|trans }}</p>

    {{ _self.ban_expires(user_ban) }}
  {% endif %}

  {% if ip_bans|length > 0 %}
    {% if user_ban %}
      <hr>
    {% endif %}

    <p>
      {{- 'banned.banned_ip'|trans({
        '%count%': ip_bans|length,
        '%formatted_count%': '<strong>%d</strong>'|format(ip_bans|length|format_number|e),
        '%ip%': '<strong>%s</strong>'|format(app.request.clientIp|e),
      })|raw -}}
    </p>

    <ul class="{{ ip_bans|length == 1 ? 'unlistify' }}">
      {% for ban in ip_bans %}
        <li>
          {% if not ban.rangeBan %}
            <p>{{ 'banned.set_on_date'|trans({ '%date%': ban.timestamp|format_date }) }}</p>
          {% else %}
            <p>{{ 'banned.set_on_date_for_range'|trans({ '%date%': ban.timestamp|format_date }) }}</p>
          {% endif %}

          {{ _self.ban_expires(ban) }}
        </li>
      {% endfor %}
    </ul>

    {% if not user_ban and (app.user.whitelistedOrAdmin ?? false) %}
      <p><strong>{{ 'banned.whitelisted'|trans }}</strong></p>
    {% endif %}
  {% endif %}
{% endblock body %}

{% macro ban_expires(ban) %}
  {% if ban.expires %}
    <p>
      {{- 'banned.will_expire'|trans({
        '%date%': ban.expires|format_datetime|e,
      }) -}}
    </p>
  {% else %}
    <p>{{ 'banned.will_not_expire'|trans }}</p>
  {% endif %}
{% endmacro ban_expires %}

templates/ban/ip_bans.html.twig
{% extends 'base.html.twig' %}

{% block title 'title.ip_bans'|trans %}
{% block site_nav_active 'admin' %}
{% block site_nav_main_menu_active 'bans' %}

{% block head %}
  {{ include('_includes/meta_pagination.html.twig', {pager: bans}, with_context = false) }}
{% endblock head %}

{% block body %}
  {{ include('ban/_tabs.html.twig', {page: 'ip_bans'}, with_context=false) }}

  <h1 class="page-heading">{{ block('title') }}</h1>

  <nav>
    <p><a href="{{ path('ban_ip') }}" class="button">{{ 'nav.add_ban'|trans }}</a></p>
  </nav>

  <form action="{{ path('unban_ips') }}" method="POST" class="form">
    <input type="hidden" name="token" value="{{ csrf_token('unban_ips') }}">

    {% embed '_layouts/table.html.twig' with { items: bans } %}
      {% block header %}
        <th class="table__shrink"></th>
        <th class="table__shrink">{{ 'label.ip_address'|trans }}</th>
        <th class="table__shrink">{{ 'ban_list.timestamp'|trans }}</th>
        <th class="table__shrink">{{ 'ban_list.expires'|trans }}</th>
        <th class="table__shrink">{{ 'ban_list.user'|trans }}</th>
        <th>{{ 'ban_list.reason'|trans }}</th>
      {% endblock header %}

      {% block row %}
        {% from '_macros/form.html.twig' import checkbox %}
        {% from '_macros/time.html.twig' import relative_time %}
        <td class="table__shrink">
          {{ checkbox({ name: 'ban[]', value: item.id, id: 'ban_'~(item.id) }) }}
        </td>
        <td class="table__shrink"><label for="ban_{{ item.id }}">{{ item.ip }}</label></td>
        <td class="table__shrink">{{ relative_time(item.timestamp, { date_format: 'short', time_format: 'none' }) }}</td>
        <td class="table__shrink">
          {% if item.expires %}
            {{ relative_time(item.expires, { date_format: 'short', time_format: 'short' }) }}
          {% else %}
            <small class="fg-muted text-sm">{{ 'ban_list.expires_never'|trans }}</small>
          {% endif %}
        </td>
        <td class="table__shrink">
          {% if item.user %}
            <a href="{{ path('user', {username: item.user.username}) }}">{{ item.user.username }}</a>
          {% else %}
            <small>{{ 'ban_list.user_none'|trans }}</small>
          {% endif %}
        </td>
        <td>{{ item.reason }}</td>
      {% endblock row %}

      {% block footer %}
        <p><button type="submit" class="button">{{ 'ban_list.remove'|trans }}</button></p>

        {{ parent() }}
      {% endblock footer %}
    {% endembed %}
  </form>
{% endblock body %}

templates/ban/unban_user.html.twig
{% extends 'base.html.twig' %}
{% from '_macros/form.html.twig' import button_row %}
{% from 'user/_macros.html.twig' import user_link %}

{% block title block('html_title')|striptags %}

{% block body %}
  {{ include('ban/_tabs.html.twig', {page: 'user_bans'}, with_context=false) }}

  <h1 class="page-heading">
    {% block html_title %}
      {{ 'title.unban_user'|trans({
        '%user%': user_link(user, {prefix: true})
      })|raw }}
    {% endblock %}
  </h1>

  {{ form_start(form) }}
    {{ form_row(form.reason) }}

    {{ form_row(form.unban_ips) }}

    {{ button_row('action.unban'|trans) }}
  {{ form_end(form) }}
{% endblock body %}

templates/ban/user_bans.html.twig
{% extends 'base.html.twig' %}

{% block title 'title.active_global_user_bans'|trans %}
{% block site_nav_active 'admin' %}
{% block site_nav_main_menu_active 'bans' %}

{% block head %}
  {{ include('_includes/meta_pagination.html.twig', {pager: bans}, with_context=false) }}
{% endblock head %}

{% block body %}
  {{ include('ban/_tabs.html.twig', {page: 'user_bans'}, with_context=false) }}

  <h1 class="page-heading">{{ block('title') }}</h1>

  {% embed '_layouts/table.html.twig' with { items: bans } %}
    {% block header %}
      <th class="table__shrink">{{ 'label.username'|trans }}</th>
      <th class="table__shrink">{{ 'label.banned_by'|trans }}</th>
      <th class="table__shrink">{{ 'label.banned'|trans }}</th>
      <th class="table__shrink">{{ 'label.expires'|trans }}</th>
      <th>{{ 'label.reason'|trans }}</th>
      <th class="table__shrink"></th>
    {% endblock header %}

    {% block row %}
      {% from '_macros/time.html.twig' import relative_time %}
      {% from 'user/_macros.html.twig' import user_link %}
      <td class="table__shrink">{{ user_link(item.user) }}</td>
      <td class="table__shrink">{{ user_link(item.bannedBy) }}</td>
      <td class="table__shrink">{{ relative_time(item.timestamp, { date_format: 'short', time_format: 'none' }) }}</td>
      <td class="table__shrink">
        {% if item.expires %}
          {{ relative_time(item.expires, { date_format: 'short', time_format: 'short' }) }}
        {% else %}
          <small class="fg-muted text-sm">{{ 'label.never'|trans }}</small>
        {% endif %}
      </td>
      <td>{{ item.reason }}</td>
      <td class="table__shrink">
        <a href="{{ path('unban_user', {username: item.user.username}) }}" class="button button--small inline">
          {{- 'action.unban'|trans -}}
        </a>
      </td>
    {% endblock row %}
  {% endembed %}
{% endblock body %}