src/Entity/CssTheme.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class CssTheme extends Theme {
    /**
     * @ORM\OneToMany(targetEntity="CssThemeRevision", mappedBy="theme", cascade={"persist", "remove"})
     * @ORM\OrderBy({"timestamp": "DESC", "id": "DESC"})
     *
     * @var CssThemeRevision
     */
    private $revisions;

    public function __construct(string $name, string $css) {
        parent::__construct($name);

        $this->revisions = new ArrayCollection();
        $this->revisions[] = new CssThemeRevision($this, $css);
    }

    public function getLatestRevision(): CssThemeRevision {
        $criteria = Criteria::create()
            ->orderBy(['timestamp' => 'DESC', 'id' => 'DESC'])
            ->setMaxResults(1);

        $revision = $this->revisions->matching($criteria)->first();

        if (!$revision) {
            throw new \DomainException(sprintf(
                'Theme %s (id=%s) does not have any revisions',
                $this->getName(),
                $this->getId()->toString()
            ));
        }

        return $revision;
    }

    public function addRevision(CssThemeRevision $revision): void {
        if (!$this->revisions->contains($revision)) {
            $this->revisions[] = $revision;
        }
    }

    public function getType(): string {
        return 'css';
    }
}

templates/_macros/alert.html.twig
{% use '_layouts/alert.html.twig' %}

{% macro alert(text, type='notice', loud=false) %}
  {{- block('alert') -}}
{% endmacro alert %}

{% macro alert_classes(type='notice') %}
  {{- block('alert_classes') -}}
{% endmacro alert_classes %}

{% macro alert_icon(type='notice') %}
  {{- block('alert_icon') -}}
{% endmacro alert_icon %}

templates/_macros/feed_macros.atom.twig
{% macro pagination(pager) %}
  {% with { route: app.request.attributes.get('_route'), params: app.request.attributes.get('_route_params') ?? {} } %}
    {% if pager.hasNextPage %}
      <link rel="next" href="{{ url(route, params|merge(pager.nextPageParams)) }}"/>
    {% endif %}
  {% endwith %}
{% endmacro %}

templates/_macros/form.html.twig
{%- macro checkbox(attributes) -%}
  {%- from '_macros/icon.html.twig' import icon -%}
  <span class="unstylable-widget">
    <input type="checkbox"
           class="{{ ('form-control '~(attributes.class ?? ''))|trim }}"
           value="{{ attributes.value ?? 'on' }}"
           {{ attributes
             |filter((v, k) => k not in ['class', 'type', 'value'])
             |map((v, k) => v is same as(true) ? k : v is same as(false) or v is null ? '' : '%s="%s"'|format(k, v|e('html_attr')))
             |join(' ')|raw }}>
    {{- icon('ok', 'X', 'icon--no-align unstylable-widget__check') -}}
  </span>
{%- endmacro checkbox -%}

{%- macro radio(attributes) -%}
  {%- from '_macros/icon.html.twig' import icon -%}
  <span class="unstylable-widget">
    <input type="radio"
           class="{{ ('form-control '~(attributes.class ?? ''))|trim }}"
           {{ attributes
             |filter((v, k) => k not in ['class', 'type'])
             |map((v, k) => v is same as(true) ? k : v is same as(false) or v is null ? '' : '%s="%s"'|format(k, v|e('html_attr')))
             |join(' ')|raw }}>
    <span class="unstylable-widget__circle" aria-hidden="true"></span>
  </span>
{%- endmacro radio -%}

{% macro button_row(label, attr={}) %}
  <div class="form__row form__button-row">
    <button class="{{ ('button '~(attr.class ?? ''))|trim }}"
      {{~ attr
        |filter((v, k) => k not in ['class'])
        |map((v, k) => v is same as(true) ? k : v is same as(false) or v is null ? '' : '%s="%s"'|format(k, v|e('html_attr')))
        |join(' ')|raw }}>
      {{- label -}}
    </button>
  </div>
{% endmacro button_row %}

templates/_macros/icon.html.twig
{% macro icon(name, alt_text = '', extra_classes='', alt_text_extra_classes='') %}
  {#- prevent preloading sprite sheet more than once -#}
  {%- set icon_asset = asset('build/images/icons.svg') -%}
  {%- if not app.request.attributes.get('icons_are_linked') -%}
    {%- set icon_asset = preload(icon_asset) -%}
  {%- endif -%}
  {%- do app.request.attributes.set('icons_are_linked', true) -%}

  {%- apply spaceless -%}
    <span class="icon {{ alt_text ? 'icon--with-alt-text' }} {{ extra_classes }}">
      {%- if alt_text is not empty -%}
        {#- Attempt to display an empty SVG. If this fails, the alt text will
            display. We assume that no support for SVG via <img> = no inline SVG
            support, although this assumption doesn't always hold true for older
            browsers (which we don't care about anyway). This hack is necessary to
            provide alternative text for Tor browser in high security mode, where
            SVG icons are disabled. -#}
            <img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%2F%3E"
                 alt="{{ alt_text }}"
                 class="icon__alt {{ alt_text_extra_classes }}"
                 aria-hidden="true"
                 width="0"
                 height="0">
      {%- endif -%}
      <svg width="16" height="16"><use xlink:href="{{ icon_asset }}#{{ name }}"/></svg>
    </span>
  {%- endapply -%}
{% endmacro icon %}

templates/_macros/lang.html.twig
{% macro lang_attributes(language) -%}
  {{- _self.lang_attribute(language) -}}
  {{- _self.dir_attribute(language) }}
{%- endmacro lang_attributes %}

{% macro lang_attribute(language) -%}
  {%- if language -%}
    {{- ' lang="%s"'|format(language|replace({ '_': '-' })|split('@')[0]|split('.')[0]|e)|raw -}}
  {%- endif -%}
{%- endmacro lang_attribute %}

{#- currently matches arabic, hebrew, yiddish -#}
{%- macro dir_attribute(language) -%}
  {%- if language -%}
    {{- ' dir="%s"'|format(language matches '/^(ar|he|yi)\\b/' ? 'rtl' : 'ltr')|raw -}}
  {%- endif -%}
{%- endmacro dir_attribute -%}

templates/_macros/post_nav.html.twig
{% macro front_post_types(current) %}
  <ul class="unlistify flex">
    <li>
      <a href="{{ path('front') }}"
         class="tab {{ current == 'submissions' ? 'tab--active' }}">
        {{- 'nav.submissions'|trans -}}
      </a>
    </li>
    <li>
      <a href="{{ path('comment_list') }}"
         class="tab {{ current == 'comments' ? 'tab--active' }}">
        {{- 'nav.comments'|trans -}}
      </a>
    </li>
  </ul>
{% endmacro front_post_types %}

{% macro forum_post_types(forum_name, current) %}
  <ul class="unlistify flex">
    <li>
      <a href="{{ path('forum', { forum_name: forum_name }) }}"
         class="tab {{ current == 'submissions' ? 'tab--active' }}">
        {{- 'nav.submissions'|trans -}}
      </a>
    </li>
    <li>
      <a href="{{ path('forum_comments', { forum_name: forum_name }) }}"
         class="tab {{ current == 'comments' ? 'tab--active' }}">
        {{- 'nav.comments'|trans -}}
      </a>
    </li>
  </ul>
{% endmacro forum_post_types %}

{% macro submission_sort(current) %}
  {% from _self import _submission_sort_items, _tab_button %}
  {% set current_label = 'submission.sort_by_%s'|format(current)|trans %}
  <li class="dropdown">
    {{ _tab_button(current_label, 'label.sort_by_mode', '%mode%', 'sort') }}

    <ul class="dropdown__menu dropdown-card unlistify">
      {{ _submission_sort_items(current, ['hot', 'new', 'active'], null) }}
      {{ _submission_sort_items(current, ['top', 'controversial', 'most_commented'], 'day') }}
    </ul>
  </li>
{% endmacro submission_sort %}

{% macro _submission_sort_items(current, types, time) %}
  {% set attr = app.request.attributes %}
  {% for type in types %}
    <li>
      <a href="{{ path(attr.get('_route'), (attr.get('_route_params') ?? [])|merge({sortBy: type, t: time})) }}"
         class="no-wrap menu-item {{ type == current ? 'menu-item--active' }}">
        {{- ('submission.sort_by_'~type)|trans -}}
      </a>
    </li>
  {% endfor %}
{% endmacro _submission_sort_items %}

{% macro submission_filter(choice, sort_by) %}
  {% from _self import _tab_button %}
  {% from '_macros/icon.html.twig' import icon %}
  {% set filter_modes = {
    featured: { label: 'front.featured'|trans },
    subscribed: { label: 'front.subscribed'|trans, condition: is_granted('ROLE_USER') },
    all: { label: 'front.all'|trans },
    moderated: { label: 'nav.moderated'|trans, condition: (app.user.moderatorTokens ?? [])|length > 0 },
  } %}
  {% set current_label = filter_modes[choice].label %}
  <li class="dropdown">
    {{ _tab_button(current_label, 'label.filter_on_mode', '%mode%', 'filter') }}

    <ul class="dropdown__menu dropdown-card unlistify">
      {% for route, mode in filter_modes|filter(mode => mode.condition ?? true) %}
        <li>
          <a href="{{ path(route, {sortBy: sort_by}) }}"
             class="no-wrap menu-item {{ choice == route ? 'menu-item--active' }}">
            {{- mode.label -}}
          </a>
        </li>
      {% endfor %}
    </ul>
  </li>
{% endmacro submission_filter %}

{% macro submission_time(sort_by) %}
  {% from _self import _tab_button %}
  {% set current = app.request.query.get('t', 'all') %}
  {% set times = constant('App\\Entity\\Submission::TIME_OPTIONS') %}
  {% if current not in times %}
    {% set current = 'all' %}
  {% endif %}
  {% if app.request.query.has('t') or sort_by not in ['active', 'hot', 'new'] %}
    {% set attr = app.request.attributes %}
    {% set current_label = 'submission.time_%s'|format(current)|trans %}
    <li class="dropdown">
      {{ _tab_button(current_label, 'label.from_time', '%time%', 'clock') }}

      <ul class="dropdown__menu dropdown-card unlistify">
        {% for time in times %}
          <li>
            <a href="{{ path(attr.get('_route'), (attr.get('_route_params') ?? [])|merge({t: time})) }}"
               class="no-wrap menu-item {{ time == current ? 'menu-item--active' }}">
              {{- ('submission.time_'~time)|trans -}}
            </a>
          </li>
        {% endfor %}
      </ul>
    </li>
  {% endif %}
{% endmacro submission_time %}

{% macro _tab_button(choice_label, label_name, label_key, icon) %}
  {% from '_macros/icon.html.twig' import icon %}
  <button type="button"
          class="dropdown__toggle tab no-underline unbuttonize"
          aria-label="{{ label_name|trans({ (label_key): choice_label }) }}">
    {{ icon(icon) }}
    <span class="no-underline__exempt">{{ choice_label }}</span>
    <span class="dropdown__arrow"></span>
  </button>
{% endmacro _tab_button %}

templates/_macros/return_nav.html.twig
{##
 # Options:
 # - raw_label (bool)
 # - attr (array): attributes to apply to the link
 #}
{% macro return_nav(label, url, options={}) -%}
  {%- from '_macros/icon.html.twig' import icon -%}
  <nav>
    <ul class="flex flex--guttered unlistify">
      <li>
        <a href="{{ url }}"
           class="flex flex--slim-gutters flex--align-center fg-text {{ options.attr.class ?? '' }}"
           {{ (options.attr ?? {})
             |filter((v, k) => k != 'class')
             |map((v, k) => v is same as(true) ? k : v is same as(false) or v is null ? '' : '%s="%s"'|format(k, v|e('html_attr')))
             |join(' ')|raw }}>
          {{ icon('left-small', '', 'icon--circled text-xl') }}
          <span class="text-lg">{{ (options.raw_label ?? false) ? (label|raw) : label }}</span>
        </a>
      </li>
    </ul>
  </nav>
{%- endmacro return_nav %}

templates/_macros/theme.html.twig
{% macro theme_css(theme=null) %}
  {% set theme = ((app.user.showCustomStylesheets ?? true) ? theme : null) ?: (app.user.preferredTheme ?? site_theme()) %}
  {% if theme and theme.type == 'css' %}
    <link rel="stylesheet" href="{{ path('theme_css', { themeId: theme.id, revisionId: theme.latestRevision.id }) }}">
  {% elseif theme and theme.type == 'bundled' or not theme %}
    {{ encore_entry_link_tags(theme_entrypoint(theme.configKey ?? '_default')) }}
  {% endif %}
{% endmacro theme_css %}

templates/_macros/time.html.twig
{% macro relative_time(datetime, options={}) -%}
  {%- set options = {
    date_format: 'long',
    time_format: 'short',
    natural: false,
    extra_classes: '',
  }|merge(options) -%}
  {%- set timezone = app.user.timezone ?? null -%}
  {%- set timestamp = datetime|format_datetime(options.date_format, options.time_format, timezone=timezone) -%}
  {%- set tip = datetime|format_datetime('long', 'long', timezone=timezone) -%}
  {%- set classes = ('js-relative-time '~options.extra_classes)|trim -%}
  <time datetime="{{ datetime|date('c') }}" class="{{ classes }}" title="{{ tip }}">
    {%- if options.natural -%}
      {{- 'time.on_timestamp'|trans({'%timestamp%': timestamp}) -}}
    {%- else -%}
      {{- timestamp -}}
    {%- endif -%}
  </time>
{%- endmacro relative_time %}

{% macro relative_time_diff(datetime, compare_to, options={}) -%}
  {%- set options = {
    date_format: 'long',
    time_format: 'short',
    natural: false,
    extra_classes: '',
  }|merge(options) -%}
  {%- set timezone = app.user.timezone ?? null -%}
  {%- set timestamp = datetime|format_datetime(options.date_format, options.time_format, timezone=timezone) -%}
  {%- set tip = datetime|format_datetime('long', 'long', timezone=timezone) -%}
  {%- set classes = ('js-relative-time-diff '~options.extra_classes)|trim -%}
  <time datetime="{{ datetime|date('c') }}" data-compare-to="{{ compare_to|date('c') }}" class="{{ classes }}" title="{{ tip }}">
    {%- if options.natural -%}
      {{- 'time.on_timestamp'|trans({'%timestamp%': timestamp}) -}}
    {%- else -%}
      {{- timestamp -}}
    {%- endif -%}
  </time>
{%- endmacro relative_time_diff %}